**Jupyter notebook_Nathalia Venancio**

*Esta atividade foi muito relevante para nosso conhecimento!*

In [1]:
import pandas as pd

In [27]:
pd.read_excel('/default_of_credit_card_clients__courseware_version_1_21_19.xls')

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,798fc410-45c1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
1,8a8c8f3b-8eb4,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,85698822-43f5,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,0737c11b-be42,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,3b7f77cc-dbc0,50000,1,2,1,57,-1,0,-1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,ecff42d0-bdc6,220000,1,3,1,39,0,0,0,0,...,88004,31237,15980,8500,20000,5003,3047,5000,1000,0
29996,99d1fa0e-222b,150000,1,3,2,43,-1,-1,-1,-1,...,8979,5190,0,1837,3526,8998,129,0,0,0
29997,95cdd3e7-4f24,30000,1,2,2,37,4,3,2,-1,...,20878,20582,19357,0,0,22000,4200,2000,3100,1
29998,00d03f02-04cd,80000,1,3,1,41,1,-1,0,0,...,52774,11855,48944,85900,3409,1178,1926,52964,1804,1
29999,15d69f9f-5ad3,50000,1,2,1,46,0,0,0,0,...,36535,32428,15313,2078,1800,1430,1000,1000,1000,1

In [57]:

df = pd.read_excel('/default_of_credit_card_clients__courseware_version_1_21_19.xls')

**Número de colunas**

In [50]:
total_colunas = df.shape[1]
print(f"Número de colunas: {total_colunas}")

Número de colunas: 25

**Número de linhas**

In [51]:
total_linhas = df.shape[0]
print(f"Número de linhas: {total_linhas}")

Número de linhas: 30000

**Tipos de características**

In [52]:
tipos = df.dtypes
print("Tipos de características:")
print(tipos)

Tipos de características:
ID                            object
LIMIT_BAL                      int64
SEX                            int64
EDUCATION                      int64
MARRIAGE                       int64
AGE                            int64
PAY_1                         object
PAY_2                          int64
PAY_3                          int64
PAY_4                          int64
PAY_5                          int64
PAY_6                          int64
BILL_AMT1                      int64
BILL_AMT2                      int64
BILL_AMT3                      int64
BILL_AMT4                      int64
BILL_AMT5                      int64
BILL_AMT6                      int64
PAY_AMT1                       int64
PAY_AMT2                       int64
PAY_AMT3                       int64
PAY_AMT4                       int64
PAY_AMT5                       int64
PAY_AMT6                       int64
default payment next month     int64
dtype: object

**Separação entre categóricas e numéricas**

In [53]:
categ_colunas = df.select_dtypes(include=['object', 'category']).columns.tolist()
num_colunas = df.select_dtypes(include=['number']).columns.tolist()
print(f"Colunas categóricas: {categ_colunas}")
print(f"Colunas numéricas: {num_colunas}")

Colunas categóricas: ['ID', 'PAY_1']
Colunas numéricas: ['LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2', 'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1', 'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6', 'default payment next month']

**Resumo dos dados numéricos**

In [54]:
descricao_numericas = df[num_colunas].describe()
print("Resumo estatístico das características numéricas:")
print(descricao_numericas)

Resumo estatístico das características numéricas:
            LIMIT_BAL           SEX     EDUCATION      MARRIAGE           AGE  \
count    30000.000000  30000.000000  30000.000000  30000.000000  30000.000000
mean    165760.989333      1.586500      1.833333      1.535900     35.108800
std     130158.590432      0.513348      0.807699      0.542698      9.851592
min          0.000000      0.000000      0.000000      0.000000      0.000000
25%      50000.000000      1.000000      1.000000      1.000000     28.000000
50%     140000.000000      2.000000      2.000000      2.000000     34.000000
75%     240000.000000      2.000000      2.000000      2.000000     41.000000
max    1000000.000000      2.000000      6.000000      3.000000     79.000000

              PAY_2         PAY_3         PAY_4         PAY_5         PAY_6  \
count  30000.000000  30000.000000  30000.000000  30000.000000  30000.000000
mean      -0.132867     -0.164333     -0.219300     -0.263900     -0.288033
std        1.191215      1.191096      1.162348      1.127519      1.144981
min       -2.000000     -2.000000     -2.000000     -2.000000     -2.000000
25%       -1.000000     -1.000000     -1.000000     -1.000000     -1.000000
50%        0.000000      0.000000      0.000000      0.000000      0.000000
75%        0.000000      0.000000      0.000000      0.000000      0.000000
max        8.000000      8.000000      8.000000      8.000000      8.000000

       ...      BILL_AMT4      BILL_AMT5      BILL_AMT6       PAY_AMT1  \
count  ...   30000.000000   30000.000000   30000.000000   30000.000000
mean   ...   42791.362167   39884.398167   38480.350933    5613.321500
std    ...   64090.316188   60606.644833   59406.836932   16539.094312
min    ... -170000.000000  -81334.000000 -339603.000000       0.000000
25%    ...    2034.000000    1534.000000    1080.000000     836.000000
50%    ...   18759.500000   17835.500000   16643.000000    2084.500000
75%    ...   53572.250000   49804.000000   48863.500000    5000.000000
max    ...  891586.000000  927171.000000  961664.000000  873552.000000

           PAY_AMT2       PAY_AMT3       PAY_AMT4       PAY_AMT5  \
count  3.000000e+04   30000.000000   30000.000000   30000.000000
mean   5.855410e+03    5174.387967    4776.089733    4754.749200
std    2.299256e+04   17565.538305   15532.893047   15239.070708
min    0.000000e+00       0.000000       0.000000       0.000000
25%    7.217500e+02     371.000000     223.000000     170.750000
50%    2.000000e+03    1776.000000    1500.000000    1500.000000
75%    5.000000e+03    4500.000000    4000.000000    4000.000000
max    1.684259e+06  896040.000000  621000.000000  426529.000000

            PAY_AMT6  default payment next month
count   30000.000000                30000.000000
mean     5164.223267                    0.218733
std     17712.664703                    0.413394
min         0.000000                    0.000000
25%         9.000000                    0.000000
50%      1500.000000                    0.000000
75%      4000.000000                    0.000000
max    528666.000000                    1.000000

[8 rows x 23 columns]

**Resumo das características categóricas**

In [55]:
for col in categ_colunas:
    print(f"Distribuição da característica categórica '{col}':")
    print(df[col].value_counts())
    print("\n")

Distribuição da característica categórica 'ID':
ID
89f8f447-fca8    2
7c9b7473-cc2f    2
90330d02-82d9    2
75938fec-e5ec    2
2a793ecf-05c6    2
                ..
bd737997-0eb0    1
6d4101a3-72cb    1
ffba3018-ce71    1
df11c637-f8c2    1
ef4d40c5-8697    1
Name: count, Length: 29687, dtype: int64


Distribuição da característica categórica 'PAY_1':
PAY_1
0                13402
-1                5047
1                 3261
Not available     3021
-2                2476
2                 2378
3                  292
4                   63
5                   23
8                   17
6                   11
7                    9
Name: count, dtype: int64

**Verificar dados faltantes**

In [58]:
dados_faltantes = df.isnull().sum()
print("Dados faltantes por coluna:")
print(dados_faltantes[dados_faltantes > 0])

Dados faltantes por coluna:
Series([], dtype: int64)